[package]
name = "exit-drop-strategy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
try-drop = { path = "../.." }

[dev-dependencies]
try-drop = { path = "../..", features = ["debugging"] }
